In [26]:
import h5py
import numpy as np
import random

def load_h5py(path):
    with h5py.File(path,"r") as hf:
        x = np.array(hf.get('matrix'))
        print(x.shape)
        x = np.transpose(x,(0,1,3,2)).reshape(x.shape[0],-1)
        y = np.array(hf.get('label'))
        return x,y
    
def sel_temp_point(batch_xs, sel_temp_points_id=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], sel_points_id=[i for i in range(20)], final_frame_nb=39):
	# print(batch_xs.shape)
	batch_xs_temp = np.array([[]]*batch_xs.shape[0])
	for i in sel_temp_points_id:
		p_id = sel_points_id.index(i)
		print(i, p_id, final_frame_nb)
		batch_xs_temp = np.append(batch_xs_temp, \
			batch_xs[:,p_id*(final_frame_nb*3):(p_id+1)*(final_frame_nb*3)], axis=1)
	return batch_xs_temp


In [13]:
train_x,train_y = load_h5py(r"C:\Users\now more\Desktop\chalearn2013\data\train.h5")
val_x,val_y = load_h5py(r"C:\Users\now more\Desktop\chalearn2013\data\val.h5")
test_x,test_y = load_h5py(r"C:\Users\now more\Desktop\chalearn2013\data\test.h5")

(6800, 19, 39, 3)
(3434, 19, 39, 3)
(3555, 19, 39, 3)


In [5]:
train_x.shape

(6800, 2223)

In [6]:
train_y.shape

(6800, 20)

In [15]:
train_y[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [20]:
t_x_train = sel_temp_point(train_x)

0 0 39
1 1 39
2 2 39
3 3 39
4 4 39
5 5 39
6 6 39
7 7 39
8 8 39
9 9 39
10 10 39


In [18]:
t_x_train.shape

(6800, 1287)

In [31]:
num,dim = np.array(t_x_train[0,:]).shape

ValueError: not enough values to unpack (expected 2, got 1)

In [36]:
trans_nb_list = [random.sample([i for i in range(-5, 5)], 1)[0] \
    for _ in range(1)]


In [37]:
trans_nb_list

[0]

In [40]:
np.random.randint(-5,5,2)

array([ 3, -4])

In [48]:
np.random.uniform(-1,1)

-0.8706027254414916

In [56]:
np.argmax(train_y,axis=1).shape

(6800,)

In [55]:
np.unique(np.argmax(train_y,axis=1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)